const DRAW_BUFFER_CARDINALITY = 255; 
const PRIZE_DISTRIBUTION_BUFFER_CARDINALITY = 60; // two months
const BEACON_START_TIME = Math.floor((new Date('2021-10-15T19:00:00.000Z')).getTime() / 1000)
const BEACON_PERIOD_SECONDS = 86400; // one day
const DRAW_CALCULATOR_TIMELOCK = 86400; // one day
const RNG_TIMEOUT_SECONDS = 2 * 3600 // 2 hours
const VALIDITY_DURATION = 60 * 86400 // 2 months
const TOKEN_DECIMALS = 6;

module.exports = {
  DRAW_BUFFER_CARDINALITY,
  PRIZE_DISTRIBUTION_BUFFER_CARDINALITY,
  BEACON_START_TIME,
  BEACON_PERIOD_SECONDS,
  DRAW_CALCULATOR_TIMELOCK,
  RNG_TIMEOUT_SECONDS,
  VALIDITY_DURATION,
  TOKEN_DECIMALS
}
